---
- name: Install HTTPD and Start HTTPD
  hosts: all
  become: root
  become_user: root
  
  tasks:

  - name: upgrade all packages
    yum: 
     name: * 
     state: latest

  - name: Install HTTPD
    yum:
      name: httpd
      state: present

  - name: Start the HTTPD
    service:
      name: httpd
      state: started
