---
- name: Linux Patching
  hosts: all  
  become: yes
  become_user: root

  tasks:
    - name: Check for updates
      yum:
        update_cache: yes  # For RHEL/CentOS

    - name: Install available updates
      yum:
        name: '*'
        state: latest  # For RHEL/CentOS

    - name: Reboot required check (distribution specific)
      command: rpm -qa --last | grep kernel  # For RHEL/CentOS
      register: reboot_required  # Capture output in a variable
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

    - name: Reboot the server (optional)
      reboot:
        post_reboot_delay: 300  # Wait 5 minutes after reboot
      when: reboot_required.stdout_lines | length > 0
